### PR TITLE
USWDS Integration

### PR DESCRIPTION
**Pull request by shumatepf**
Download and upload all USWDS assets following the USWDS [download and install guide](https://github.com/uswds/uswds#download-and-install). Add allow all CORS header to resolve existing CORS issues in the IDVA environment.

### CODE REVIEW

**Comment by dzaslavskiy** [comment]
Are we customizing uswds? If not, would it make sense to just referance one of the public cdns hosting uswds?

**Comment by shumatepf** [comment]
> Are we customizing uswds?

Instead of customizing we are maintaining a static version

**Comment by folksgl** [comment]
I share @dzaslavskiy's sentiment here. If the goal is to reference an unmodified version of USWDS, I doubt that requires us to host our own repo with all the assets, right?

**Comment by shumatepf** [comment]
Ah my PR description does not include the full purpose that it should have - 
Our current solution uses 3rd party USWDS components that are out of sync, not within our control to change, and are difficult to request changes for. Hosting it ourselves is a simple solution and mitigates these issues entirely.

This is a common issue it seems, but there is no official cdn for USWDS right now.
uswds/uswds#4298

**Comment by dzaslavskiy** [comment]
Can we use a public cdn like: https://cdnjs.com/libraries/uswds or are we going to host it ourselves?

**Review by dzaslavskiy — APPROVED** [review]

**Pull request merged**
